/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContainersIndexRouteImport } from './routes/containers/index'
import { Route as ContainersContainerIdExecRouteImport } from './routes/containers/$containerId/exec'
import { Route as ContainersContainerIdAttachRouteImport } from './routes/containers/$containerId/attach'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersIndexRoute = ContainersIndexRouteImport.update({
  id: '/containers/',
  path: '/containers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersContainerIdExecRoute =
  ContainersContainerIdExecRouteImport.update({
    id: '/containers/$containerId/exec',
    path: '/containers/$containerId/exec',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContainersContainerIdAttachRoute =
  ContainersContainerIdAttachRouteImport.update({
    id: '/containers/$containerId/attach',
    path: '/containers/$containerId/attach',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/containers': typeof ContainersIndexRoute
  '/containers/$containerId/attach': typeof ContainersContainerIdAttachRoute
  '/containers/$containerId/exec': typeof ContainersContainerIdExecRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/containers': typeof ContainersIndexRoute
  '/containers/$containerId/attach': typeof ContainersContainerIdAttachRoute
  '/containers/$containerId/exec': typeof ContainersContainerIdExecRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/containers/$containerId/attach': typeof ContainersContainerIdAttachRoute
  '/containers/$containerId/exec': typeof ContainersContainerIdExecRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/containers'
    | '/containers/$containerId/attach'
    | '/containers/$containerId/exec'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/containers'
    | '/containers/$containerId/attach'
    | '/containers/$containerId/exec'
  id:
    | '__root__'
    | '/'
    | '/containers/'
    | '/containers/$containerId/attach'
    | '/containers/$containerId/exec'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainersIndexRoute: typeof ContainersIndexRoute
  ContainersContainerIdAttachRoute: typeof ContainersContainerIdAttachRoute
  ContainersContainerIdExecRoute: typeof ContainersContainerIdExecRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/': {
      id: '/containers/'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$containerId/exec': {
      id: '/containers/$containerId/exec'
      path: '/containers/$containerId/exec'
      fullPath: '/containers/$containerId/exec'
      preLoaderRoute: typeof ContainersContainerIdExecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$containerId/attach': {
      id: '/containers/$containerId/attach'
      path: '/containers/$containerId/attach'
      fullPath: '/containers/$containerId/attach'
      preLoaderRoute: typeof ContainersContainerIdAttachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainersIndexRoute: ContainersIndexRoute,
  ContainersContainerIdAttachRoute: ContainersContainerIdAttachRoute,
  ContainersContainerIdExecRoute: ContainersContainerIdExecRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
